FROM opencog/cogutil
MAINTAINER Enkusellasie Wendwosen <enku@singularitynet.io>

#Run apt-get in NONINTERACTIVE mode
ENV DEBIAN_FRONTEND noninteractive
ENV HOME /root
WORKDIR $HOME

RUN git clone https://github.com/opencog/atomspace.git
WORKDIR atomspace
RUN git checkout e463209c43594b60050c013c94261c1a6604035e
RUN mkdir build
WORKDIR build
RUN \
    cmake .. && \
    make && \
    make install

WORKDIR $HOME

RUN git clone https://github.com/opencog/opencog.git
WORKDIR opencog
RUN mkdir build
WORKDIR build
RUN \
    cmake .. && \
    make && \
    make install

WORKDIR $HOME

#Install pyenv and use it for managing python version
RUN curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
ENV PYENV_ROOT $HOME/.pyenv
ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
RUN pyenv install 3.5.2
RUN pyenv virtualenv 3.5.2 general
RUN pyenv global general
ENV PYTHONPATH /usr/local/lib/python3.5/dist-packages:/usr/local/lib/python3/dist-packages:$PYTHONPATH


RUN git clone https://github.com/Habush/agi-bio.git
WORKDIR agi-bio
RUN mkdir build
WORKDIR build
RUN \
    cmake .. && \
    make && \
    make install


WORKDIR $HOME
RUN git clone https://github.com/MOZI-AI/guile-json.git
WORKDIR guile-json
RUN \
    apt-get install -y dh-autoreconf && \
    autoreconf -vif && \
    ./configure  && \
    make && \
    make install


#setup grpc proxy
WORKDIR $HOME
ENV GRPC_PROXY_V 0.9.1
RUN apt-get install unzip
RUN wget -O grpc-proxy.zip https://github.com/improbable-eng/grpc-web/releases/download/v$GRPC_PROXY_V/grpcwebproxy-v$GRPC_PROXY_V-linux-x86_64.zip
RUN unzip grpc-proxy.zip && mv dist/grpcwebproxy-v$GRPC_PROXY_V-linux-x86_64 ./ && mv grpcwebproxy-v$GRPC_PROXY_V-linux-x86_64 grpc-proxy && rm grpc-proxy.zip
RUN chmod 755 grpc-proxy
